Sign/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
] 

urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

app/urls.py
from django.urls import path
from app.views import index,EngineerSide,LoadEngineerDataInPdf,UpdateFormView,DetailFormView,EngineersReportsList

app_name= "app"
urlpatterns = [
    path('',EngineerSide.as_view(),name="home"),
    path('return/',index,name="return"),
    path('update/<id>/',UpdateFormView.as_view(), name="update"),
    path('detail/<id>/',DetailFormView.as_view(), name="detail"),

    path('<int:id>/',LoadEngineerDataInPdf, name = "loadDrawing"),

    path('pendinglist/',EngineersReportsList.as_view(),name="pendinglist")

]

app/forms.py
from django import forms
from crispy_forms.helper import FormHelper
import re
from django.http import HttpResponse
from django.forms import ModelForm, HiddenInput
from crispy_forms.layout import Layout, Submit, Row, Column

import base64
import random
from .models import Engineer

class EngineerForm(forms.Form):
    engineersign_data = forms.CharField(widget=forms.HiddenInput())
    CUSTOMER = forms.CharField(label='', max_length=100)
    STORE = forms.CharField(label="",max_length=100)
    STORE_NO = forms.CharField(label="",max_length=100)
    CALL_OUT_NO = forms.CharField(label="",max_length=100)

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_id = "agreement_form"
        self.helper.form_method = 'post'
        super(EngineerForm, self).__init__(*args, **kwargs)

    def save(self):
        engineer_data = Engineer(
            engineersign = self.cleaned_data['engineersign_data'],
            CUSTOMER = self.cleaned_data['CUSTOMER'],
            STORE = self.cleaned_data['STORE'],
            STORE_NO = self.cleaned_data['STORE_NO'],
            CALL_OUT_NO = self.cleaned_data['CALL_OUT_NO'],

            )
        engineer_data.save()
        # print(engineer_data.id)
        return engineer_data

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        labels = ['CUSTOMER','STORE','STORE_NO','CALL_OUT_NO']
        for label in labels:
            self.fields[label].widget.attrs['placeholder'] = label

        # self.fields['CUSTOMER'].widget.attrs['placeholder'] = 'CUSTOMER'
        # self.fields['STORE'].widget.attrs['placeholder'] = 'STORE'
        # self.fields['STORE_NO'].widget.attrs['placeholder'] = 'STORE NO'
        # self.fields['CALL_OUT_NO'].widget.attrs['placeholder'] = 'CALL OUT NO.'




    #     self.helper.layout = Layout(
    #         Row(
    #             Column('CUSTOMER',css_class='form-group col-md-6 mb-0'),
    #             Column('CUSTOMER', css_class='form-group col-md-6 mb-0'),
    #             css_class='form-row'
    #         ),
    #         'CUSTOMER',
    #         'CUSTOMER',
    #         Row(
    #             Column('CUSTOMER', css_class='form-group col-md-6 mb-0'),
    #             Column('CUSTOMER', css_class='form-group col-md-4 mb-0'),
    #             Column('CUSTOMER', css_class='form-group col-md-2 mb-0'),
    #             css_class='form-row'
    #         ),
    #         'CUSTOMER',
    #         Submit('submit', 'Sign in')
    #     ) 

class EngineerUpdateForm(forms.ModelForm):
    managersign_data = forms.CharField(widget=forms.HiddenInput(), required=False)
    
    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_id = "agreement_form"
        self.helper.form_method = 'post'
        super(EngineerUpdateForm, self).__init__(*args, **kwargs)
        
        labels = ['engineersign','managersign','CUSTOMER','STORE','STORE_NO','CALL_OUT_NO']
        for label in labels:
            self.fields[label].widget=HiddenInput()
        # self.fields['CUSTOMER'].widget=HiddenInput()
        # self.fields['STORE'].widget=HiddenInput()
        # self.fields['engineersign'].widget=HiddenInput()
        # self.fields['managersign'].widget=HiddenInput()
        # self.fields['STORE_NO'].widget=HiddenInput()
        # self.fields['CALL_OUT_NO'].widget=HiddenInput()

    # def save(self):
    #     ads = Engineer(
    #         managersign = self.cleaned_data['managersign_data'],
    #         )
    #     ads.save()
    #     # print(engineer_data.id)
    #     return ads
    class Meta:
        model = Engineer
        fields = ['engineersign','CUSTOMER','STORE','STORE_NO','CALL_OUT_NO','managersign']

templates/EngineerSide.html
{% load crispy_forms_tags %}
 
<!doctype html>
<html lang="en">
<head>
    <title>Document!</title>
     <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/0.4.1/html2canvas.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.11.0.min.js"></script>
   </head>
<body>









<center><h1>Engineer Side</h1></center></p>
<div class="wrapper">
  <center><canvas id="signature-pad" class="signature-pad" width=1000 height=200 style="border:5px solid #000000;"></canvas></center>
</div>
  
  <center><button id="draw">Draw</button>
  <button id="clear">Clear</button></center>  

  <center><h3>Enter Firstname and Lastname{% crispy form %}</h3></center>
<center><button type="button" id="submit">Save</button></center>


















<script src="https://cdn.jsdelivr.net/npm/signature_pad@2.3.2/dist/signature_pad.min.js"></script>
<script>
var canvas = document.getElementById('signature-pad');

var signaturePad = new SignaturePad(canvas, {
  backgroundColor: 'rgb(255, 255, 255)' // necessary for saving image as JPEG; can be removed is only saving as PNG or SVG
});

document.getElementById('clear').addEventListener('click', function () {
  signaturePad.clear();
});

document.getElementById('draw').addEventListener('click', function () {
  var ctx = canvas.getContext('2d');
  console.log(ctx.globalCompositeOperation);
  ctx.globalCompositeOperation = 'source-over'; // default value
});


</script>


<script type="text/javascript">
        $('#submit').click(function(){
            html2canvas(document.getElementById('signature-pad'),
            {
              onrendered: function (canvas) {
                engineersign_data = canvas.toDataURL('image/jpeg');
 
                $('#id_engineersign_data').val(engineersign_data);
                $('#agreement_form').submit();
              }
            });
          });
</script>
    













  <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/EngineersReportsList.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/base.css' %}">
<h1 style="float: right;"><a href="/">Return to home page</a></h1>
<h1>MANAGER SIDE</h1>
<center><h1>Pending Reports For Review</h1></center>
<div class="container">
	{% for object in object_list %}
		{% if object.managersign == None or object.managersign == "" %}
		<div class="sub">
			<a class="link" href="{% url 'app:update' object.id %}">Click To Review</a>
			<h2>Engineer-sign : </h2>
			<img src="{{object.engineersign}}" style="cursor: pointer; border: 1px solid rgb(199, 200, 201); height: 150px; width: 300px; border-radius: 5px;">
			<h2>CUSTOMER Name : <span>{{object.CUSTOMER}}</span></h2> 
			<h2>STORE No : <span>{{object.STORE_NO}}</span></h2>
		</div>
		{% endif %}
	{% endfor %}
</div>

templates/detail.html
<h1><a href="/">Return to home page</a></h1>


<h3>Engineer-sign : <img src="{{object.engineersign}}" style="cursor: pointer; border: 1px solid rgb(199, 200, 201); height: 150px; width: 300px; border-radius: 5px;"></h3>




<h3>CUSTOMER Name : {{object.CUSTOMER}}</h3>



<h3>STORE : {{object.STORE}}</h3>
<h3>STORE No : {{object.STORE_NO}}</h3>
<h3>manager-sign :
<img src="{{object.managersign}}" style="cursor: pointer; border: 1px solid rgb(199, 200, 201); height: 150px; width: 300px; border-radius: 5px;"></h3><br/>

templates/index.html
<h1>Success Report submitted</h1>
<h1><a href="/">Return to home page</a></h1>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/">About</a>
      </li>
  
         </ul>
  
  </div>
</nav>